// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOdDTtkKKVXQL8h4mn1PNutVUkSRJAgW4',
    appId: '1:977115377033:web:1a87be458047a0846e4558',
    messagingSenderId: '977115377033',
    projectId: 'flutterfirstproject-9b992',
    authDomain: 'flutterfirstproject-9b992.firebaseapp.com',
    storageBucket: 'flutterfirstproject-9b992.appspot.com',
    measurementId: 'G-2W1NXQ1GC6',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH4FcWN-B9_DHZQjUq_bHyockUzrQbPa8',
    appId: '1:977115377033:android:dd4be255cf5c64eb6e4558',
    messagingSenderId: '977115377033',
    projectId: 'flutterfirstproject-9b992',
    storageBucket: 'flutterfirstproject-9b992.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkidB3EVXH_bGOX0PwheLS2qiaA4s4Nvw',
    appId: '1:977115377033:ios:6428038e4084c17b6e4558',
    messagingSenderId: '977115377033',
    projectId: 'flutterfirstproject-9b992',
    storageBucket: 'flutterfirstproject-9b992.appspot.com',
    iosBundleId: 'com.edugaon.getexTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkidB3EVXH_bGOX0PwheLS2qiaA4s4Nvw',
    appId: '1:977115377033:ios:6428038e4084c17b6e4558',
    messagingSenderId: '977115377033',
    projectId: 'flutterfirstproject-9b992',
    storageBucket: 'flutterfirstproject-9b992.appspot.com',
    iosBundleId: 'com.edugaon.getexTest',
  );
}
